---
# roles/download/tasks/main.yml
- name: Creates directory
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ dl_path }}"
    - "{{ vm_path }}"

- name: download latest raspbian
  get_url: 
    url: "{{ raspbian_url }}"
    dest: "{{ dl_path }}"
    timeout: 30
  register: dl_result

#- fail: 
#    msg: Error while downloading "{{ dl_result.url }}",
#  when: 


- name: unzip archive
  unarchive:
    src: "{{ dl_result.dest }}"
    dest: "{{ vm_path }}"

